### PR TITLE
auto-correct port collision in Vagrantfile

### PR DESCRIPTION
**Pull request by davidhuser**

### CODE REVIEW

**Comment by davidhuser** [comment]
@alanthing not sure if you were tagged previously

**Comment by alanivey** [comment]
Would you be able to update this PR to include the same setting for the other published ports?

**Comment by davidhuser** [comment]
done @alanthing

**Comment by alanivey** [comment]
Verified:

```
$ { screen -d -m nc -l 0.0.0.0 5432
    screen -d -m nc -l 0.0.0.0 8080
    screen -d -m nc -l 0.0.0.0 8888 ; }

$ netstat -an | grep -e 5432 -e 8888 -e 8080

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'bento/centos-7' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 5432 => 5432. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 5432 (guest) => 2200 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 80 (guest) => 8888 (host) (adapter 1)
... snip ...

$ psql -Upostgres -h127.0.0.1 -p2200
psql (10.5, server 10.6)
Type "help" for help.

postgres=# \conninfo
You are connected to database "postgres" as user "postgres" on host "127.0.0.1" at port "2200".
```

**Pull request closed without merging**
